export const PROFIL_USER = 'PROFIL_USER';
export const PROFIL_USER_SUCCESS = 'PROFIL_USER_SUCCESS';
export const PROFIL_USER_ERROR = 'PROFIL_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
